# Generated by Django 2.2.7 on 2020-03-02 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='creaded',
            new_name='created',
        ),
    ]
